Ext.define('Mario.model.Movie',{
    extend:'Ext.data.Model',
    fields:[{
        name:'title',
        type:'string'
    },{
        name:'tns',
        type:'string'
    },{
        name:'url',
        type:'string'
    },{
        name:'author',
        type:'string'
    },{
        name:'duration',
        type:'float'
    },{
        name:'releaseDate',
        type:'date',
        formatDate:'Y-m-d'
    },{
        name:'description',
        type:'string'
    }]
});

