Ext.define('Mario.store.Movies',{
    extend:'Ext.data.Store',
    model:'Mario.model.Movie',
    proxy:{
        url:'../../data/movies.json',
        reader:{
            type:'json',
            root:'data'
        }
    }
});