Ext.define('Mario.store.Movies',{
    extend:'Ext.data.Store',
    model:'Mario.model.Movie',
    autoLoad:true,
    proxy:{
        type:'ajax',
        url:'data/movies.json',
        reader:{
            type:'json',
            root:'data'
        }
    }
});